# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 512)
        MainWindow.setMinimumSize(QtCore.QSize(512, 512))
        self.MainWindow_widget = QtWidgets.QWidget(MainWindow)
        self.MainWindow_widget.setObjectName("MainWindow_widget")
        self.MainWindow_widget_Layout = QtWidgets.QGridLayout(self.MainWindow_widget)
        self.MainWindow_widget_Layout.setObjectName("MainWindow_widget_Layout")
        self.Output_textEdit = QtWidgets.QTextEdit(self.MainWindow_widget)
        self.Output_textEdit.setObjectName("Output_textEdit")
        self.MainWindow_widget_Layout.addWidget(self.Output_textEdit, 7, 0, 1, 1)
        self.Generate_button = QtWidgets.QPushButton(self.MainWindow_widget)
        self.Generate_button.setObjectName("Generate_button")
        self.MainWindow_widget_Layout.addWidget(self.Generate_button, 6, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.MainWindow_widget)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Block_0 = QtWidgets.QWidget()
        self.Block_0.setObjectName("Block_0")
        self.Block_0_Layout = QtWidgets.QGridLayout(self.Block_0)
        self.Block_0_Layout.setObjectName("Block_0_Layout")
        self.Block_0_comboBox = QtWidgets.QComboBox(self.Block_0)
        self.Block_0_comboBox.setMinimumSize(QtCore.QSize(80, 20))
        self.Block_0_comboBox.setObjectName("Block_0_comboBox")
        self.Block_0_comboBox.addItem("")
        self.Block_0_comboBox.addItem("")
        self.Block_0_comboBox.addItem("")
        self.Block_0_Layout.addWidget(self.Block_0_comboBox, 0, 1, 1, 1)
        self.Block_0_DelimeterLineEdit = QtWidgets.QLineEdit(self.Block_0)
        self.Block_0_DelimeterLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.Block_0_DelimeterLineEdit.setMaximumSize(QtCore.QSize(80, 20))
        self.Block_0_DelimeterLineEdit.setObjectName("Block_0_DelimeterLineEdit")
        self.Block_0_Layout.addWidget(self.Block_0_DelimeterLineEdit, 0, 0, 1, 1)
        self.Block_0_BlockName = QtWidgets.QLineEdit(self.Block_0)
        self.Block_0_BlockName.setMinimumSize(QtCore.QSize(0, 20))
        self.Block_0_BlockName.setText("")
        self.Block_0_BlockName.setObjectName("Block_0_BlockName")
        self.Block_0_Layout.addWidget(self.Block_0_BlockName, 0, 2, 1, 1)
        self.Block_0_textEdit = QtWidgets.QTextEdit(self.Block_0)
        self.Block_0_textEdit.setObjectName("Block_0_textEdit")
        self.Block_0_Layout.addWidget(self.Block_0_textEdit, 1, 0, 1, 3)
        self.tabWidget.addTab(self.Block_0, "")
        self.MainWindow_widget_Layout.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.MainWindow_widget_horizontalLayout = QtWidgets.QHBoxLayout()
        self.MainWindow_widget_horizontalLayout.setObjectName("MainWindow_widget_horizontalLayout")
        self.SaveProjectButton = QtWidgets.QPushButton(self.MainWindow_widget)
        self.SaveProjectButton.setObjectName("SaveProjectButton")
        self.MainWindow_widget_horizontalLayout.addWidget(self.SaveProjectButton)
        self.LoadProjectButton = QtWidgets.QPushButton(self.MainWindow_widget)
        self.LoadProjectButton.setObjectName("LoadProjectButton")
        self.MainWindow_widget_horizontalLayout.addWidget(self.LoadProjectButton)
        self.AddBlockButton = QtWidgets.QPushButton(self.MainWindow_widget)
        self.AddBlockButton.setObjectName("AddBlockButton")
        self.MainWindow_widget_horizontalLayout.addWidget(self.AddBlockButton)
        self.MainWindow_widget_Layout.addLayout(self.MainWindow_widget_horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.MainWindow_widget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Output_textEdit, self.Generate_button)
        MainWindow.setTabOrder(self.Generate_button, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.SaveProjectButton)
        MainWindow.setTabOrder(self.SaveProjectButton, self.LoadProjectButton)
        MainWindow.setTabOrder(self.LoadProjectButton, self.AddBlockButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Generate_button.setText(_translate("MainWindow", "Generieren"))
        self.Block_0_comboBox.setItemText(0, _translate("MainWindow", "random"))
        self.Block_0_comboBox.setItemText(1, _translate("MainWindow", "shuffle"))
        self.Block_0_comboBox.setItemText(2, _translate("MainWindow", "origin"))
        self.Block_0_DelimeterLineEdit.setPlaceholderText(_translate("MainWindow", "Delimeter"))
        self.Block_0_BlockName.setPlaceholderText(_translate("MainWindow", "Block name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Block_0), _translate("MainWindow", "MainBlock"))
        self.SaveProjectButton.setText(_translate("MainWindow", "SaveProject"))
        self.LoadProjectButton.setText(_translate("MainWindow", "LoadProject"))
        self.AddBlockButton.setText(_translate("MainWindow", "AddBlock"))
